name:                hypercube
version:             0.1.0.0
homepage:            https://github.com/githubuser/hypercube#readme
license:             GPL-3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web
extra-source-files:
- README.md

ghc-options:
 - -O2

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - lens
  - stm
  - OpenGL
  - linear
  - vector
  - containers
  - deepseq
  - thyme
  - vector-space
  - GLFW-b
  - bytestring
  - GLUtil

library:
  source-dirs: src

executables:
  hypercube:
    source-dirs:      app
    main:             Main.hs
    dependencies:     hypercube
    ghc-options:      -threaded
