name:                hypercube
version:             0.1.0.0
homepage:            https://github.com/noughtmare/hypercube#readme
license:             GPL-3
author:              Jaro Reinders
maintainer:          noughtmare@openmailbox.org
copyright:           2017 Jaro Reinders
category:            Game
extra-source-files:
- README.md

ghc-options:
 - -O2
 - -Wall

dependencies:
  - base >= 4.7 && < 5
  - transformers
  - lens
  - stm
  - OpenGL
  - linear
  - vector
  - containers
  - deepseq
  - thyme
  - vector-space
  - GLFW-b
  - bytestring
  - GLUtil
  - MemoTrie

library:
  source-dirs: src

executables:
  hypercube:
    source-dirs:        app
    main:               Main.hs
    dependencies:       hypercube
    ghc-options:        -threaded
