resolver: lts-9.1

packages:
- '.'
- location:
    git: https://github.com/noughtmare/GLUtil
    commit: a7276db223d0295ffeed790be59760ccce061db5
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []

